# Generated by Django 4.1.1 on 2022-10-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='name',
            new_name='guestname',
        ),
    ]
